window.CAN_SEED_DATA = {
  "version": 4,
  "settings": {
    "allianceName": "CAN",
    "stateNumber": "2578",
    "cjTeamSize": 6,
    "rankingMinimum": 5
  },
  "members": [
    {
      "id": "member-1",
      "name": "AngryMarshmallow",
      "gaia": 1,
      "bt": "BT2",
      "strength": "1.1B",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-2",
      "name": "Asuka",
      "gaia": 2,
      "bt": "BT2",
      "strength": "515M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-3",
      "name": "Lucky Meow",
      "gaia": 3,
      "bt": "BT2",
      "strength": "912M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-4",
      "name": "Dr.CutyRose",
      "gaia": 4,
      "bt": "BT1",
      "strength": "753M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-5",
      "name": "SmittySlaps",
      "gaia": 5,
      "bt": "BT2",
      "strength": "789M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-6",
      "name": "Bun",
      "gaia": 6,
      "bt": "BT1",
      "strength": "568M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-7",
      "name": "Space_balls",
      "gaia": 7,
      "bt": "BT1",
      "strength": "657M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-8",
      "name": "Jbsnow",
      "gaia": 8,
      "bt": "BT1",
      "strength": "574M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-9",
      "name": "Cute BRS",
      "gaia": 9,
      "bt": "BT2",
      "strength": "619M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-10",
      "name": "Hedder",
      "gaia": 10,
      "bt": "BT1",
      "strength": "634M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-11",
      "name": "Rellik",
      "gaia": 11,
      "bt": "BT2",
      "strength": "505M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-12",
      "name": "MatDNK",
      "gaia": 12,
      "bt": "BT1",
      "strength": "570M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-13",
      "name": "BuRyAbAy",
      "gaia": 13,
      "bt": "BT2",
      "strength": "583M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-14",
      "name": "Kals Avarys",
      "gaia": 14,
      "bt": "BT1",
      "strength": "520M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-15",
      "name": "Kkoma",
      "gaia": 15,
      "bt": "BT2",
      "strength": "602M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-16",
      "name": "Brother Yatty",
      "gaia": 16,
      "bt": "BT1",
      "strength": "492M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-17",
      "name": "Ntina",
      "gaia": 17,
      "bt": "BT1",
      "strength": "560M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-18",
      "name": "YahuKimo",
      "gaia": 18,
      "bt": "BT2",
      "strength": "590M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-19",
      "name": "Choppy",
      "gaia": 19,
      "bt": "BT2",
      "strength": "609M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-20",
      "name": "Tara",
      "gaia": 20,
      "bt": "BT1",
      "strength": "612M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-21",
      "name": "Eurokeith",
      "gaia": 21,
      "bt": "BT2",
      "strength": "609M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-22",
      "name": "Summer",
      "gaia": 22,
      "bt": "BT2",
      "strength": "504M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-23",
      "name": "Seal",
      "gaia": 23,
      "bt": "BT1",
      "strength": "525M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-24",
      "name": "Fu2fa2",
      "gaia": 24,
      "bt": "BT2",
      "strength": "492M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-25",
      "name": "Cat",
      "gaia": 25,
      "bt": "BT1",
      "strength": "474M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-26",
      "name": "Filip1031",
      "gaia": 26,
      "bt": "BT2",
      "strength": "589M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-27",
      "name": "Lord McLord",
      "gaia": 27,
      "bt": "BT1",
      "strength": "576M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-28",
      "name": "Ibra",
      "gaia": 28,
      "bt": "BT2",
      "strength": "550M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-29",
      "name": "Dr.cutyMomo",
      "gaia": 29,
      "bt": "BT1",
      "strength": "604M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-30",
      "name": "SKY",
      "gaia": 30,
      "bt": "BT1",
      "strength": "550M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-31",
      "name": "Tembakau ACEH",
      "gaia": 31,
      "bt": "BT2",
      "strength": "516M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-32",
      "name": "Soraa",
      "gaia": 32,
      "bt": "BT2",
      "strength": "609M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-33",
      "name": "ReyGattuso",
      "gaia": 33,
      "bt": "BT1",
      "strength": "554M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-34",
      "name": "Spike",
      "gaia": 34,
      "bt": "BT1",
      "strength": "415M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-35",
      "name": "Floopy",
      "gaia": 35,
      "bt": "BT2",
      "strength": "563M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-36",
      "name": "Black Rooster",
      "gaia": 36,
      "bt": "BT1",
      "strength": "543M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-37",
      "name": "Batavia",
      "gaia": 37,
      "bt": "BT1",
      "strength": "525M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-38",
      "name": "Ranji",
      "gaia": 38,
      "bt": "BT1",
      "strength": "500M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-39",
      "name": "Seren",
      "gaia": 39,
      "bt": "BT1",
      "strength": "454M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-40",
      "name": "Yaya_Bings",
      "gaia": 40,
      "bt": "BT1",
      "strength": "522M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-41",
      "name": "WINGJACK",
      "gaia": 41,
      "bt": "BT1",
      "strength": "602M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-42",
      "name": "U Chicken Me",
      "gaia": 42,
      "bt": "BT1",
      "strength": "472M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-43",
      "name": "Psycho",
      "gaia": 43,
      "bt": "BT2",
      "strength": "603M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-44",
      "name": "Tdvt25",
      "gaia": 44,
      "bt": "BT1",
      "strength": "604M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-45",
      "name": "Lord Vegnagun",
      "gaia": 45,
      "bt": "BT1",
      "strength": "553M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-46",
      "name": "Lilyballs",
      "gaia": 46,
      "bt": "BT1",
      "strength": "468M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-47",
      "name": "累累~累累~",
      "gaia": 47,
      "bt": "BT2",
      "strength": "470M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-48",
      "name": "NicolePharmD",
      "gaia": 48,
      "bt": "BT1",
      "strength": "631M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-49",
      "name": "Kidbull x suzume",
      "gaia": 49,
      "bt": "BT2",
      "strength": "499M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-50",
      "name": "Kuman",
      "gaia": 50,
      "bt": "BT2",
      "strength": "562M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-51",
      "name": "AZOZKA",
      "gaia": 51,
      "bt": "BT1",
      "strength": "501M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-52",
      "name": "Lexie",
      "gaia": 52,
      "bt": "BT2",
      "strength": "390M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-53",
      "name": "Blank",
      "gaia": 53,
      "bt": "BT2",
      "strength": "476M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-54",
      "name": "Meli",
      "gaia": 54,
      "bt": "BT2",
      "strength": "479M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-55",
      "name": "Melonlord",
      "gaia": 55,
      "bt": "BT1",
      "strength": "491M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-56",
      "name": "Ratchin",
      "gaia": 56,
      "bt": "BT2",
      "strength": "495M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-57",
      "name": "Doom Balls",
      "gaia": 57,
      "bt": "BT1",
      "strength": "498M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-58",
      "name": "SOGEKING",
      "gaia": 58,
      "bt": "BT2",
      "strength": "538M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-59",
      "name": "Bani Adam",
      "gaia": 59,
      "bt": "BT2",
      "strength": "371M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-60",
      "name": "Wolf Pup",
      "gaia": 60,
      "bt": "BT2",
      "strength": "525M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-61",
      "name": "Shoushana",
      "gaia": 61,
      "bt": "BT2",
      "strength": "441M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-62",
      "name": "五濁惡世",
      "gaia": 62,
      "bt": "BT2",
      "strength": "318M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-63",
      "name": "Vrekmontt",
      "gaia": 63,
      "bt": "BT1",
      "strength": "509M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-64",
      "name": "SHDW",
      "gaia": 64,
      "bt": "BT2",
      "strength": "515M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-65",
      "name": "RANGERS",
      "gaia": 65,
      "bt": "BT2",
      "strength": "469M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-66",
      "name": "Nebulese",
      "gaia": 66,
      "bt": "BT2",
      "strength": "587M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-67",
      "name": "SteelCityInsider",
      "gaia": 67,
      "bt": "BT1",
      "strength": "484M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-68",
      "name": "Wildkid",
      "gaia": 68,
      "bt": "BT2",
      "strength": "383M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-69",
      "name": "Punni",
      "gaia": 69,
      "bt": "BT2",
      "strength": "458M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-70",
      "name": "Timmu",
      "gaia": 70,
      "bt": "BT1",
      "strength": "510M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-71",
      "name": "Atiba",
      "gaia": 71,
      "bt": "BT1",
      "strength": "446M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-72",
      "name": "DODGE06",
      "gaia": 72,
      "bt": "BT2",
      "strength": "536M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-73",
      "name": "Kayzersoze77",
      "gaia": 73,
      "bt": "BT1",
      "strength": "455M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-74",
      "name": "VKdViKing",
      "gaia": 74,
      "bt": "BT1",
      "strength": "409M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-75",
      "name": "Mana",
      "gaia": 75,
      "bt": "BT2",
      "strength": "532M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-76",
      "name": "Euphoria",
      "gaia": 76,
      "bt": "BT2",
      "strength": "431M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-77",
      "name": "Durzu",
      "gaia": 77,
      "bt": "BT1",
      "strength": "540M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-78",
      "name": "Gritsayenko",
      "gaia": 78,
      "bt": "BT2",
      "strength": "382M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-79",
      "name": "Noura",
      "gaia": 79,
      "bt": "BT1",
      "strength": "398M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-80",
      "name": "JC",
      "gaia": 80,
      "bt": "BT2",
      "strength": "517M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-81",
      "name": "Chuso Faawk",
      "gaia": 81,
      "bt": "BT1",
      "strength": "431M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-82",
      "name": "Deus Caeli",
      "gaia": 82,
      "bt": "BT2",
      "strength": "460M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-83",
      "name": "Sukuna",
      "gaia": 83,
      "bt": "BT2",
      "strength": "468M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-84",
      "name": "DonMeloooon",
      "gaia": 84,
      "bt": "BT1",
      "strength": "389M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-85",
      "name": "Shore enough",
      "gaia": 85,
      "bt": "BT1",
      "strength": "369M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-86",
      "name": "Biiiiiiiiing~O",
      "gaia": 86,
      "bt": "BT1",
      "strength": "478M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-87",
      "name": "SHIBUYA",
      "gaia": 87,
      "bt": "BT1",
      "strength": "436M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-88",
      "name": "Fatchuck7",
      "gaia": 88,
      "bt": "BT1",
      "strength": "388M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-89",
      "name": "Doomsday",
      "gaia": 89,
      "bt": "BT1",
      "strength": "444M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-90",
      "name": "Pukie",
      "gaia": 90,
      "bt": "BT1",
      "strength": "363M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-91",
      "name": "fckck",
      "gaia": 91,
      "bt": "BT2",
      "strength": "417M",
      "foundry": "Legion 1",
      "canyon": "Legion 1",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    },
    {
      "id": "member-92",
      "name": "DarthVader",
      "gaia": 92,
      "bt": "BT1",
      "strength": "443M",
      "foundry": "Legion 2",
      "canyon": "Legion 2",
      "status": "Active",
      "region": "Unknown/Mixed",
      "notes": ""
    }
  ],
  "events": [],
  "messages": [
    {
      "id": "guide-cj",
      "type": "Guide",
      "title": "Crazy Joe Rules",
      "content": "Mark each member YES, SUB, or OFF, then generate balanced teams by Gaia rank."
    },
    {
      "id": "guide-foundry",
      "type": "Guide",
      "title": "Foundry Strategy",
      "content": "Legion 1 and Legion 2 are separate events. Use the permanent six-group objective structure."
    },
    {
      "id": "guide-canyon",
      "type": "Guide",
      "title": "Canyon Strategy",
      "content": "Plan opening assignments for Teams A–F. Officers adapt after the opening territory is secured."
    }
  ]
};
